### ISSUE TITLE
Fix it! 🔨

### ISSUE THREAD

**Issue by srujandeshpande** [acmpesuecc/tictactoe#4]
This code was written 2 years ago and is likely broken. It is very easy to understand. Get it to run, you can make changes in any files as required.
Show a mentor this tictactoe working on your vscode instance to get your PR approved. You are also free to add new features as desired

**Comment by Sohoxic** [comment]
Hello, I am Soham Sarkar, Sophomore at PES UNIVERSITY  representing team Fantastic FOSS and I want to work on this issue.

Thank You

**Comment by n1haldev** [comment]
Hello, I am Nihal T M, Sophomore at PES UNIVERSITY representing team Code Junkies and I want to work on this issue.

Thank You

**Comment by srujandeshpande** [comment]
@n1haldev @Sohoxic, I've fixed the repo and pushed the changes in #7. The repo should directly work as is now
